import { env } from "cloudflare:workers";
import { ensureRunStore, getD1 } from "@/db";
import { can, configuredAdmins, resolveRole } from "@/lib/auth/roles";
import { deliverAlert } from "@/lib/alerts/delivery";
export const dynamic="force-dynamic";
function config(){const w=env as unknown as {SCHEDULER_SECRET?:string;ALERT_WEBHOOK_URL?:string;ALERT_WEBHOOK_SECRET?:string;AUTOMATION_ADMIN_USER_IDS?:string};return{scheduler:w.SCHEDULER_SECRET??process.env.SCHEDULER_SECRET,webhookUrl:w.ALERT_WEBHOOK_URL??process.env.ALERT_WEBHOOK_URL,webhookSecret:w.ALERT_WEBHOOK_SECRET??process.env.ALERT_WEBHOOK_SECRET,admins:configuredAdmins(w.AUTOMATION_ADMIN_USER_IDS??process.env.AUTOMATION_ADMIN_USER_IDS)};}
function user(request:Request){const id=request.headers.get("oai-authenticated-user-id");if(id)return id;const h=new URL(request.url).hostname;return h==="localhost"||h==="127.0.0.1"?"local-demo-user":null;}
async function authorized(request:Request){const c=config();if(c.scheduler&&request.headers.get("authorization")===`Bearer ${c.scheduler}`)return true;const id=user(request);if(!id)return false;const db=getD1();await ensureRunStore(db);return can(await resolveRole(db,id,c.admins),"dispatch_alerts");}
export async function GET(request:Request){if(!(await authorized(request)))return Response.json({error:"forbidden"},{status:403});try{const db=getD1();await ensureRunStore(db);const result=await db.prepare("SELECT status, COUNT(*) AS count FROM alert_outbox GROUP BY status").all<{status:string;count:number}>();return Response.json({scheduler:"ready",webhookConfigured:Boolean(config().webhookUrl&&config().webhookSecret),outbox:result.results??[]});}catch{return Response.json({error:"scheduler_unavailable"},{status:503});}}
export async function POST(request:Request){if(!(await authorized(request)))return Response.json({error:"forbidden"},{status:403});try{const db=getD1();await ensureRunStore(db);const now=new Date().toISOString();await db.prepare("UPDATE automation_jobs SET status = 'queued', updated_at = ?, lease_expires_at = NULL WHERE status = 'running' AND lease_expires_at < ?").bind(now,now).run();const waiting=await db.prepare("SELECT owner_id, COUNT(*) AS count FROM automation_jobs WHERE status = 'human_required' GROUP BY owner_id").all<{owner_id:string;count:number}>();const hour=now.slice(0,13);for(const row of waiting.results??[]){const id=`${row.owner_id}:intervention_waiting:${hour}`;await db.prepare("INSERT OR IGNORE INTO alert_outbox (id, owner_id, alert_code, severity, status, attempts, next_attempt_at, created_at, updated_at) VALUES (?, ?, 'intervention_waiting', 'warning', 'pending', 0, ?, ?, ?)").bind(id,row.owner_id,now,now,now).run();}
const c=config();let sent=0,failed=0;if(c.webhookUrl&&c.webhookSecret){const pending=await db.prepare("SELECT id, owner_id, alert_code, severity, attempts FROM alert_outbox WHERE status IN ('pending','failed') AND next_attempt_at <= ? ORDER BY created_at LIMIT 20").bind(now).all<{id:string;owner_id:string;alert_code:string;severity:string;attempts:number}>();for(const alert of pending.results??[]){try{await deliverAlert({url:c.webhookUrl,secret:c.webhookSecret,payload:{id:alert.id,code:alert.alert_code,severity:alert.severity,occurredAt:now}});await db.prepare("UPDATE alert_outbox SET status='sent', attempts=attempts+1, updated_at=?, last_error=NULL WHERE id=?").bind(now,alert.id).run();sent++;}catch(error){const next=new Date(Date.now()+Math.min(3600000,60000*2**alert.attempts)).toISOString();await db.prepare("UPDATE alert_outbox SET status='failed', attempts=attempts+1, next_attempt_at=?, updated_at=?, last_error=? WHERE id=?").bind(next,now,error instanceof Error?error.message.slice(0,200):"delivery failed",alert.id).run();failed++;}}}
return Response.json({tick:"complete",recoveredLeases:true,alertsQueued:(waiting.results??[]).length,sent,failed,webhookConfigured:Boolean(c.webhookUrl&&c.webhookSecret)});}catch{return Response.json({error:"scheduler_failed"},{status:500});}}
